OrdererOrgs:
  - Name: Orderer
    Domain: ictu.edu.vn
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Ibn
    Domain: ibn.ictu.edu.vn
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Partner1
    Domain: partner1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Partner2
    Domain: partner2.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
