Organizations:
  - &OrdererOrg
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/example.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"

  - &Ibn
      Name: IbnMSP
      ID: IbnMSP
      MSPDir: crypto-config/peerOrganizations/ibn.ictu.edu.vn/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('IbnMSP.admin', 'IbnMSP.peer', 'IbnMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('IbnMSP.admin', 'IbnMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('IbnMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('IbnMSP.peer')"
      AnchorPeers:
          - Host: peer0.ibn.ictu.edu.vn
            Port: 7051

  - &Partner1
      Name: Partner1MSP
      ID: Partner1MSP
      MSPDir: crypto-config/peerOrganizations/partner1.example.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Partner1MSP.admin', 'Partner1MSP.peer', 'Partner1MSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('Partner1MSP.admin', 'Partner1MSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('Partner1MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Partner1MSP.peer')"
      AnchorPeers:
          - Host: peer0.partner1.example.com
            Port: 8051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Ibn
                    - *Partner1
    
    ChannelProfile:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Ibn
                - *Partner1
            Capabilities:
                <<: *ApplicationCapabilities
